### ISSUE TITLE
Nix template

### ISSUE THREAD

**Issue by srid** [leptos-rs/awesome-leptos#10]
I'd like to add https://github.com/srid/leptos-fullstack here for those people who already use Nix and wish to try out Leptos. What would be a good section to put this under?

**Comment by gbj** [comment]
Oh yes, of course! We should probably make a "Starter Templates" section which has https://github.com/leptos-rs/start, https://github.com/leptos-rs/start-axum, https://github.com/leptos-rs/start-axum-workspace, and yours!
