### ISSUE TITLE
Add `tracing-subscriber-wasm` and `wasm-bindgen-struct`

### ISSUE THREAD

**Issue by jquesada2016** [leptos-rs/awesome-leptos#2]
Requesting to add 2 crates which are not directly related to the `leptos` project, but can definitely make working with WASM easier. Perhaps under a `quality of life` section?

- [`tracing-subscriber-wasm`](https://crates.io/crates/tracing-subscriber-wasm)
- [`wasm-bindgen-struct`](https://crates.io/crates/wasm-bindgen-struct)

**Comment by gbj** [comment]
¡Por supuesto!
