### ISSUE TITLE
Add leptos-rs/start-aws to "Starter Templates" section

### ISSUE THREAD

**Issue by diversable** [leptos-rs/awesome-leptos#24]
now that the `start–AWS` starter is in the Leptos organization, please consider adding that template under the "Starter Templates" heading - although, I'm a little fuzzy on whether it should be listed under 'official' or 'unofficial'..?

cf. https://github.com/leptos-rs/start-aws

**Comment by gbj** [comment]
Done! https://github.com/leptos-rs/awesome-leptos/commit/ecda1ed3a9d47a4f4f3a76509b8237d73518ab3a
